### ISSUE TITLE
   2 | program capacit       | 1 Error: Non-numeric character in statement label at (1) 

### ISSUE THREAD

**Issue by Haoui-Hamza** [IonicaBizau/node-fortran#10]
i'm getting this for all the lines of my code 

(base) macs-MacBook-Pro:nodefortran mac$ node index.js
/var/folders/6g/mrdn4qhd7q5344ld8xcxzy5h0000gn/T/tmp-979jbS4OjXw5X7z.f:2:1:

    2 | program capacit
      | 1
Error: Non-numeric character in statement label at (1)
/var/folders/6g/mrdn4qhd7q5344ld8xcxzy5h0000gn/T/tmp-979jbS4OjXw5X7z.f:3:1:

    3 | implicit double precision(a-h,o-z,l,m)
      | 1
Error: Non-numeric character in statement label at (1)
/var/folders/6g/mrdn4qhd7q5344ld8xcxzy5h0000gn/T/tmp-979jbS4OjXw5X7z.f:4:1:

    4 | pi=2*asin(1.)
      | 1
Error: Non-numeric character in statement label at (1)
/var/folders/6g/mrdn4qhd7q5344ld8xcxzy5h0000gn/T/tmp-979jbS4OjXw5X7z.f:5:2:

**Comment by IonicaBizau** [comment]
I speculate there is an issue with the fortran code itself, rather than with the bridge.
